# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cole O'Brien Tech Art
tagline:          'Techart and Animation'
description:      'My Portfolio and Blog for Animation and Tech Art'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Cole O''Brien'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
excerpt_separator:    <!--more-->

#Gems
gems:
  - jekyll-paginate
  - jekyll-gist