# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cole O'Brien
tagline:          "Technical Art and Animation"
description:      "My Portfolio and Blog for Animation and Technical Art"
url:              https://coleobrienart.com
baseurl:          '/'
author:           "Cole OBrien"
name:             "Cole OBrien"

paginate: 10
paginate_path: "/blog/page:num/"

# Custom vars
version:          2.1.0
force_https:          true

github:
  repo:           https://github.com/obriencole11/obriencole11.github.io
excerpt_separator:    <!--more-->
show_related_posts:   false
google_analytics: UA-104250424-1

# SEO
twitter:
  username:        cole_obrien
  url: https://twitter.com/cole_obrien

logo:              /blog/assets/logo.png

social:
  name: Cole OBrien
  links:
    - https://twitter.com/cole_obrien
    - https://www.facebook.com/cole.obrien.754
    - https://www.linkedin.com/in/cole-o-brien-7b8561b0/
    - https://github.com/obriencole11

#Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag