# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Fredrik Averpil
tagline:              My personal blog
description:          My personal blog – on Python development, 3D graphics, compositing and photography.
url:                  https://fredrikaverpil.github.io
baseurl:
paginate:             5
name:                 Fredrik Averpil

#Gems
gems:
  - jekyll-paginate
  - jekyll-gist