# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cole<br/>O'Brien<strong>Art</strong>
tagline:          'Techart and Animation'
description:      'My Portfolio and Blog for <strong>Animation</strong> and <strong>Technical Art</strong>'
url:              https://obriencole11.github.io
baseurl:          /

author:
  name:           'Cole OBrien'
  url:            https://twitter.com/

paginate: 5
paginate_path: "/blog/page:num/"

# Custom vars
version:          2.1.0
force_https:          true

github:
  repo:           https://github.com/poole/hyde
excerpt_separator:    <!--more-->
show_related_posts:   false

#Gems
gems:
  - jekyll-paginate
  - jekyll-gist